# Requirement: add a K8S_SECRET secret to your organization with the SA token
# Bind the SA with a cluster-admin Role
# oc get secret backstage-k8s-token-4l5xv -n backstage-system -oyaml > secret.yaml
# gh secret --repo parodos-dev/test-swf set K8S_SECRET <secret.yaml 
name: Deploy the Pipeline trigger manifests workflow

on:
  workflow_dispatch:
    inputs:
      workflowId:
        description: 'Workflow Id'
        required: true
        type: string
      gitConfigUrl:
        description: 'URL of git config repo'
        required: true
        type: string
      tektonNamespace:
        description: 'Namespace of Tekton resources'
        required: true
        type: string
        default: 'sonataflow-infra'
      argocdNamespace:
        description: 'Namespace of ArgoCD resources'
        required: true
        type: string
        default: 'argocd'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: default
          insecure_skip_tls_verify: true

      - name: Deploy Tekton trigger to the Kubernetes cluster
        run: |
          oc apply -n ${{ inputs.tektonNamespace }} -f tekton
      
      - name: Deploy ArgoCD application to the Kubernetes cluster
        run: |
          oc apply -n ${{ inputs.argocdNamespace }} -f argocd
      - name: Create ArgoCD repository
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sshPrivateKey
          cat sshPrivateKey
          oc create secret -n ${{ inputs.argocdNamespace }} generic "${{ inputs.workflowId }}-repo" \
            --from-literal name=${{ inputs.workflowId }} \
            --from-literal project=orchestrator \
            --from-literal type=git \
            --from-literal url=${{ inputs.gitConfigUrl }} \
            --from-file=sshPrivateKey
          oc label secret -n ${{ inputs.argocdNamespace }} "${{ inputs.workflowId }}-repo" argocd.argoproj.io/secret-type=repository
      
      # To be reviewed: needs a private repo to skip the need of a PR 
      # - name: Commit a change to trigger the webhook
      #   run: |
      #     echo $(date) > tekton/trigger
      #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #     git config --global user.name "${{ github.actor }}"
      #     git add tekton/trigger
      #     git commit --no-verify -m "Webhook trigger"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
    