apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
__RESOURCES__
namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: ${{ values.workflowId }}-secret
configMapGenerator:
  - envs:
      - config.properties
    name: ${{ values.workflowId }}-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: ${{ values.workflowId }}
images:
- name: serverless-workflow-${{ values.workflowId }}
  newName: quay.io/orchestrator/serverless-workflow-${{ values.workflowId }}
  newTag: __IMAGE_TAG__
